packages:
  - "tools" #工具层：提供构建、lint、类型检查等统一工程能力
  - "packages/*" #共享基础层
  - "apps/*" #应用层
  - "!**/__tests__/**"
  - "!**/dist/**"

catalog:
  react: ^18.3.1
  redux: ^5.0.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1

catalogs:
  webpack:
    html-webpack-plugin: ^5.6.4
    ts-loader: ^9.5.2
    webpack: ^5.101.3
    webpack-cli: ^6.0.1

  rollup:
    "@rollup/plugin-babel": ^6.0.4
    "@rollup/plugin-node-resolve": ^16.0.1
    rollup: ^4.48.1
    rollup-plugin-commonjs: ^1.1.0
    "@rollup/plugin-typescript": ^10.0.1
    "@rollup/plugin-alias": ^5.1.1
    "@rollup/plugin-json": ^6.1.0
    rollup-plugin-terser: ^7.0.2
