packages:
  - "tools" #工具层：提供构建、lint、类型检查等统一工程能力
  - "packages/*" #共享基础层
  - "apps/*" #应用层
  - "!**/__tests__/**"
  - "!**/dist/**"

catalog:
  react: ^18.3.1
  redux: ^5.0.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.1
  "@types/react-dom": ^18.3.1

catalogs:
  webpack:
    html-webpack-plugin: ^5.6.4
    ts-loader: ^9.5.2
    webpack: ^5.101.3
    webpack-cli: ^6.0.1
